name: Deploy Authentication Dev

on:
  workflow_run:
    workflows: ["Python tests authentication"]
    branches: [preprod]
    types:
      - completed
  workflow_dispatch:
    branches:
      - kip/*

env:
  AWS_REGION: eu-west-2 # set this to your preferred AWS region, e.g. us-west-1

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy authentication
        uses: ./.github/templates/deploy/
        with:
          folder: authentication
          env: dev
          service_name: backend
      - name: Deploy Redis
        uses: ./.github/templates/deploy/
        with:
          folder: authentication
          env: dev
          service_name: redis
